/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoSO;

/**
 *
 * @author mkferrerteran
 */
public class ventanatxt extends javax.swing.JPanel {

    /**
     * Creates new form ventanatxt
     */
    public ventanatxt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollsTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        modificarRolls = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rollsTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 494, -1, -1));

        rollsTextArea.setColumns(20);
        rollsTextArea.setRows(5);
        jScrollPane1.setViewportView(rollsTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 300, 270));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Archivo TXT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        modificarRolls.setForeground(new java.awt.Color(0, 102, 153));
        modificarRolls.setText("Modificar");
        add(modificarRolls, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        rollsTextArea1.setColumns(20);
        rollsTextArea1.setRows(5);
        jScrollPane2.setViewportView(rollsTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 300, 270));

        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Modificar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Archivo TXT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Sirve2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 488));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificarRolls;
    private javax.swing.JTextArea rollsTextArea;
    private javax.swing.JTextArea rollsTextArea1;
    // End of variables declaration//GEN-END:variables
}
